# Generated by Django 6.0 on 2026-03-31 11:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_nguoidung', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thongtinnguoidung',
            name='id',
        ),
        migrations.AlterField(
            model_name='thongtinnguoidung',
            name='id_user',
            field=models.ForeignKey(db_column='id_nguoi_dung', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
