# Generated by Django 6.0 on 2026-03-31 12:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_nguoidung', '0002_remove_thongtinnguoidung_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thongtinnguoidung',
            name='id_user',
            field=models.OneToOneField(db_column='id_nguoi_dung', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
