# Generated by Django 6.0 on 2026-04-01 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_nguoidung', '0003_alter_thongtinnguoidung_id_user'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nguoidung',
            name='google_id',
        ),
        migrations.AddField(
            model_name='thongtinnguoidung',
            name='country',
            field=models.CharField(db_column='quoc_gia', max_length=50, null=True, verbose_name='Quốc gia'),
        ),
        migrations.AddField(
            model_name='thongtinnguoidung',
            name='role',
            field=models.CharField(choices=[('Đối tác', 'Đối tác'), ('Khách hàng', 'Khách hàng')], db_column='vai_tro', max_length=10, null=True, verbose_name='Vai trò'),
        ),
        migrations.AlterField(
            model_name='nguoidung',
            name='groups',
            field=models.ManyToManyField(help_text='Các nhóm mà người dùng này thuộc về.', related_name='nguoi_dung_set', related_query_name='nguoi_dung', to='auth.group', verbose_name='Nhóm quyền'),
        ),
        migrations.AlterField(
            model_name='nguoidung',
            name='last_login',
            field=models.DateTimeField(db_column='lan_dang_nhap_cuoi', null=True, verbose_name='Lần đăng nhập cuối'),
        ),
        migrations.AlterField(
            model_name='nguoidung',
            name='user_permissions',
            field=models.ManyToManyField(help_text='Các quyền được gán trực tiếp cho người dùng này.', related_name='nguoi_dung_set', related_query_name='nguoi_dung', to='auth.permission', verbose_name='Quyền riêng'),
        ),
        migrations.AlterField(
            model_name='thongtinnguoidung',
            name='first_name',
            field=models.CharField(db_column='ten', max_length=150, null=True, verbose_name='Tên'),
        ),
        migrations.AlterField(
            model_name='thongtinnguoidung',
            name='last_name',
            field=models.CharField(db_column='ho', max_length=150, null=True, verbose_name='Họ'),
        ),
    ]
