# Generated by Django 6.0 on 2026-04-01 14:22

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KhachSan',
            fields=[
                ('id_hotel', models.UUIDField(db_column='ma_khach_san', editable=False, primary_key=True, serialize=False)),
                ('slug_hotel', models.SlugField(db_column='slug_khach_san', max_length=80, unique=True)),
                ('name_hotel', models.CharField(db_column='ten_khach_san', max_length=60)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, db_column='vi_tri', geography=True, null=True, srid=4326)),
            ],
            options={
                'db_table': 'khach_san',
            },
        ),
    ]
