# Generated by Django 6.0 on 2026-03-31 11:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='NguoiDung',
            fields=[
                ('id_user', models.UUIDField(db_column='id_nguoi_dung', default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('email', models.EmailField(error_messages={'unique': 'Email này đã tồn tại.'}, max_length=254, unique=True, verbose_name='email')),
                ('email_verified_at', models.DateTimeField(db_column='lan_xac_nhan_email', null=True, verbose_name='Lần xác nhận email')),
                ('google_id', models.CharField(max_length=50, null=True)),
                ('password', models.CharField(db_column='mat_khau', max_length=128, verbose_name='Mật khẩu')),
                ('auth_type', models.CharField(max_length=10, null=True)),
                ('is_staff', models.BooleanField(db_column='nhan_vien', default=False, help_text='Quy định người dùng có thể đăng nhập vào trang quản trị hay không.', verbose_name='Nhân viên')),
                ('is_active', models.BooleanField(db_column='dang_hoat_dong', default=True, help_text='Bỏ chọn thay vì xóa tài khoản.', verbose_name='Đang hoạt động')),
                ('is_superuser', models.BooleanField(db_column='quan_tri_vien', default=False, help_text='Có toàn bộ quyền mà không cần gán cụ thể.', verbose_name='Quản trị viên')),
                ('last_login', models.DateTimeField(blank=True, db_column='lan_dang_nhap_cuoi', null=True, verbose_name='Lần đăng nhập cuối')),
                ('last_updated', models.DateTimeField(auto_now=True, db_column='lan_cap_nhat_cuoi', null=True, verbose_name='Lần cập nhật cuối')),
                ('date_joined', models.DateTimeField(auto_now_add=True, db_column='ngay_tham_gia', verbose_name='Ngày tham gia')),
                ('groups', models.ManyToManyField(blank=True, help_text='Các nhóm mà người dùng này thuộc về.', related_name='nguoi_dung_set', related_query_name='nguoi_dung', to='auth.group', verbose_name='Nhóm quyền')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Các quyền được gán trực tiếp cho người dùng này.', related_name='nguoi_dung_set', related_query_name='nguoi_dung', to='auth.permission', verbose_name='Quyền riêng')),
            ],
            options={
                'db_table': 'nguoi_dung',
            },
        ),
        migrations.CreateModel(
            name='ThongTinNguoiDung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, db_column='ten', max_length=150, verbose_name='Tên')),
                ('last_name', models.CharField(blank=True, db_column='ho', max_length=150, verbose_name='Họ')),
                ('id_user', models.ForeignKey(db_column='id_nguoi_dung', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'thongtin_nguoidung',
            },
        ),
    ]
